### ISSUE TITLE
Ability to save as HTML or interactive PDF?

### ISSUE THREAD

**Issue by mm-gmbd** [zoellner/openapi-preview#2]
Ability to save as HTML or an interactive PDF would be fantastic (cleaner way of sharing these docs sometimes).

I tried choosing "Save As" but it doesn't bring up a save dialog.

Thanks for the extension!

**Comment by zoellner** [comment]
Thank you for that suggestion. I haven't come across the need myself yet but just looked into supporting printing as I think it would be useful. 
Unfortunately it looks like Visual Studio Code doesn't have native print support. The OpenAPI Preview uses the builtin webview component to render the preview, so there is no easy solution to add print support to this extension.

You could try one of the print extensions that are on the Visual Studio Marketplace to see if that works for you: https://marketplace.visualstudio.com/search?term=printing&target=VSCode

**Comment by zoellner** [comment]
As mentioned in #3 VS Code doesn't support printing at all, so I am going to close this one.
