### ISSUE TITLE
How do I use the preview?

### ISSUE THREAD

**Issue by carlpaton** [zoellner/openapi-preview#9]
Brother I want to use your plug-in but cannot figure out how to use the preview?

[Docs state](https://github.com/zoellner/openapi-preview/blob/master/README.md):

**Usage**
Open the main OpenAPI YAML file.
Run the Command ⇧⌘P OpenAPI Preview.

What does ⇧⌘P mean?

Perhaps include screen shots for people like me that cannot follow simple instructions :)

Im on windows if it helps.

Cheers!

**Comment by zoellner** [comment]
That is the shortcut to open the "Command Palette". I think it is "Ctrl+Shift+P" on Windows
